### ISSUE TITLE
Coq 8.6 and 8.7

### ISSUE THREAD

**Issue by ejgallego** [parametricity-coq/paramcoq#7]
Hi, what is the plan to port this plugin to 8.6 / 8.7 ?

I could help but it would be great if we synchronize @drouhling , @CohenCyril , I think you already had an 8.6 port?

Cheers, E.

**Comment by ejgallego** [comment]
cc @aa755

**Comment by aa755** [comment]
I have an 8.6 port that also contains some bugfixes.

https://github.com/aa755/paramcoq/commits/v86FullNames

**Comment by ejgallego** [comment]
Cool, how does it interact with #6 ? Should maybe be merged on the main repository ?

**Comment by ejgallego** [comment]
Note that the GADT `Sigma` bits have been removed from 8.7

**Comment by ejgallego** [comment]
By the way, as soon as we get this running in 8.7 I will add it to Coq Travis; however, in order to do so we would somebody willing to "maintain" the plugin: basically merging PR Coq developers may submit in a timely fashion.

**Comment by ejgallego** [comment]
Closing this, I think @aa755 has a current port.
